blank_issues_enabled: false
contact_links:
  - name: Support Server
    url: https://discord.gg/nFRHhDk
    about: If you need help with anything, join our support server and ask in the appropriated channel.
